# Generated by Django 4.0.4 on 2022-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='in Nigerian N', max_digits=15),
        ),
    ]
